---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-service
  labels:
    author: intelliqit
spec:
  type: NodePort
  ports:
    - targetPort: 2368
      port: 80
      nodePort: 30008
  selector:
    app: cms
